### ISSUE TITLE
MessageID

### ISSUE THREAD

**Issue by Trifunik** [insighio/microCoAPy#4]
Hi,
I am using your lib as a client for a small project of mine --> https://github.com/Trifunik/condensation_alert.
Do you know any elegant way to get the coapPacket.messageid from the get function?
I want to be sure that the payload is the response to the wright GET request, because I have sometimes a race condition between two GET requests.

Many thanks in advance!
Nikola

**Comment by ftylitak** [comment]
Hello @Trifunik 

You are looking for a way to get the **coapPacket.messageid** of a GET function and I will suppose that you require the messageid of the request packet. Correct? 

If this is indeed true, then the _messsageid_ of the request packet is the integer value returned by the **client.get** function. 

Note here that the example in our source code has a typo. At the print of the return value of the get function, it is named as payload which should be replaced with _messageid_.

example:

```python
import microcoapy
# your code to connect to the network
#...
def receivedMessageCallback(packet, sender):
        print('Message received:', packet, ', from: ', sender)
        print('Mesage payload: ', packet.payload.decode('unicode_escape'))
        print('Response ID: ', packet.messageid.decode('unicode_escape'))

client = microcoapy.Coap()
client.resposeCallback = receivedMessageCallback
client.start()

_SERVER_IP="192.168.1.2"
_SERVER_PORT=5683
requestId= client.get(_SERVER_IP, _SERVER_PORT, "current/measure")
print("[GET] Request ID: ", requestId)

client.poll(2000)

client.stop()
```

**Comment by ftylitak** [comment]
Update: according to the CoAP specification, the messageid is mainly used for dublicate message detection and optional reliability in case of losses. On the other hand, __token is used for request/response matching__. 

Based on this info, I will go over our implementation to see if it needs adjustments.

**Comment by ftylitak** [comment]
@Trifunik 
As a respose to your question, after a proper code review, the correct approach is to use the token field to match request/respose pairs. 

The functions [get](https://github.com/insighio/microCoAPy/wiki#getip-port-url-token), [put](https://github.com/insighio/microCoAPy/wiki#putip-port-url-payloa-queryoption-content_format-token), [post](https://github.com/insighio/microCoAPy/wiki#postip-port-url-payload-queryoption-content_format-token) have been updated to support a **token** parameter. Thus, if you provide as a last argument a *token* byte array, this exact token must exist in the corresponding response. 

To get the new functionality please pull the latest changes from master. Be aware of some minor [breaking changes at parameter names](https://github.com/insighio/microCoAPy#breaking-change-02-01-2020).

Does this approach solves your request?

**Comment by Trifunik** [comment]
Thank you!
Yes, I did not look good enough at your GET function. Because I saw in the example "bytesTransferred = client.get(...)" and thought I have to look somewhere else.

**Comment by ftylitak** [comment]
Yes unfortunatelly it was a misleading typo.

**Comment by ftylitak** [comment]
@Trifunik 

as soon as you test it in your project and you need no further changes, could you close the issue? 

Regards.
